#!/usr/bin/env php
<?php

use Library\Application\App;

ini_set('display_errors', '1');
error_reporting(E_ALL);

require 'vendor/autoload.php';

try {
	App::init(__DIR__);
	$exitCode = App::run($argv);
}
catch (Throwable $e) {
	fprintf(STDERR, PHP_EOL . $e->getMessage());
	fprintf(STDERR, PHP_EOL . $e->getTraceAsString());
	$exitCode = 1;
}

exit($exitCode);
